INSERT INTO procedure_codes (ada_code, description, abbreviated_desc, category, default_fee) VALUES
-- Diagnostic (D0100-D0999)
('D0120', 'Periodic oral evaluation - established patient', 'Periodic eval', 'Diagnostic', 55.00),
('D0140', 'Limited oral evaluation - problem focused', 'Limited eval', 'Diagnostic', 75.00),
('D0150', 'Comprehensive oral evaluation - new or established patient', 'Comp eval', 'Diagnostic', 95.00),
('D0210', 'Intraoral - complete series of radiographic images', 'FMX', 'Diagnostic', 175.00),
('D0220', 'Intraoral - periapical first radiographic image', 'PA first', 'Diagnostic', 35.00),
('D0230', 'Intraoral - periapical each additional radiographic image', 'PA addl', 'Diagnostic', 25.00),
('D0272', 'Bitewing radiographic image - two images', 'BWX 2', 'Diagnostic', 65.00),
('D0274', 'Bitewing radiographic image - four images', 'BWX 4', 'Diagnostic', 95.00),
('D0330', 'Panoramic radiographic image', 'Pano', 'Diagnostic', 155.00),
('D0470', 'Diagnostic casts', 'Study models', 'Diagnostic', 85.00),
-- Preventive (D1000-D1999)
('D1110', 'Prophylaxis - adult', 'Prophy adult', 'Preventive', 105.00),
('D1120', 'Prophylaxis - child', 'Prophy child', 'Preventive', 75.00),
('D1206', 'Topical application of fluoride varnish', 'Fluoride varnish', 'Preventive', 40.00),
('D1208', 'Topical application of fluoride - excluding varnish', 'Fluoride', 'Preventive', 35.00),
('D1310', 'Nutritional counseling for control of dental disease', 'Nutritional counsel', 'Preventive', 45.00),
('D1320', 'Tobacco counseling for the control and prevention of oral disease', 'Tobacco counsel', 'Preventive', 45.00),
('D1351', 'Sealant - per tooth', 'Sealant', 'Preventive', 55.00),
('D1510', 'Space maintainer - fixed - unilateral - per quadrant', 'Space maint fixed', 'Preventive', 295.00),
-- Restorative (D2000-D2999)
('D2140', 'Amalgam restoration - one surface, primary or permanent', 'Amalgam 1S', 'Restorative', 155.00),
('D2150', 'Amalgam restoration - two surfaces, primary or permanent', 'Amalgam 2S', 'Restorative', 195.00),
('D2160', 'Amalgam restoration - three surfaces, primary or permanent', 'Amalgam 3S', 'Restorative', 235.00),
('D2161', 'Amalgam restoration - four or more surfaces, primary or permanent', 'Amalgam 4S+', 'Restorative', 275.00),
('D2391', 'Resin-based composite - one surface, posterior - primary or permanent', 'Composite 1S post', 'Restorative', 195.00),
('D2392', 'Resin-based composite - two surfaces, posterior - primary or permanent', 'Composite 2S post', 'Restorative', 245.00),
('D2393', 'Resin-based composite - three surfaces, posterior - primary or permanent', 'Composite 3S post', 'Restorative', 295.00),
('D2394', 'Resin-based composite - four or more surfaces, posterior - primary or permanent', 'Composite 4S+ post', 'Restorative', 345.00),
('D2710', 'Crown - resin-based composite (indirect)', 'Crown composite', 'Restorative', 895.00),
('D2720', 'Crown - resin with high noble metal', 'PFM HN crown', 'Restorative', 1095.00),
('D2740', 'Crown - porcelain/ceramic substrate', 'All ceramic crown', 'Restorative', 1195.00),
('D2750', 'Crown - porcelain fused to high noble metal', 'PFM HN', 'Restorative', 1095.00),
('D2751', 'Crown - porcelain fused to predominantly base metal', 'PFM base', 'Restorative', 895.00),
('D2752', 'Crown - porcelain fused to noble metal', 'PFM noble', 'Restorative', 995.00),
-- Endodontic (D3000-D3999)
('D3310', 'Endodontic therapy, anterior tooth (excluding final restoration)', 'RCT anterior', 'Endodontic', 795.00),
('D3320', 'Endodontic therapy, premolar tooth (excluding final restoration)', 'RCT premolar', 'Endodontic', 895.00),
('D3330', 'Endodontic therapy, molar tooth (excluding final restoration)', 'RCT molar', 'Endodontic', 1095.00),
('D3346', 'Retreatment of previous root canal therapy - anterior', 'RCT retreat ant', 'Endodontic', 995.00),
('D3347', 'Retreatment of previous root canal therapy - premolar', 'RCT retreat pre', 'Endodontic', 1095.00),
('D3348', 'Retreatment of previous root canal therapy - molar', 'RCT retreat mol', 'Endodontic', 1295.00),
('D3410', 'Apicoectomy - anterior', 'Apicoectomy ant', 'Endodontic', 895.00),
('D3421', 'Apicoectomy - premolar (first root)', 'Apicoectomy pre', 'Endodontic', 895.00),
('D3425', 'Apicoectomy - molar (first root)', 'Apicoectomy mol', 'Endodontic', 995.00),
('D3426', 'Apicoectomy - (each additional root)', 'Apicoectomy addl', 'Endodontic', 295.00),
-- Periodontic (D4000-D4999)
('D4210', 'Gingivectomy or gingivoplasty - four or more contiguous teeth per quadrant', 'Gingivectomy 4+', 'Periodontic', 595.00),
('D4211', 'Gingivectomy or gingivoplasty - one to three contiguous teeth per quadrant', 'Gingivectomy 1-3', 'Periodontic', 395.00),
('D4240', 'Gingival flap procedure, including root planing - four or more contiguous teeth per quadrant', 'Flap 4+', 'Periodontic', 795.00),
('D4241', 'Gingival flap procedure, including root planing - one to three contiguous teeth per quadrant', 'Flap 1-3', 'Periodontic', 595.00),
('D4260', 'Osseous surgery - four or more contiguous teeth per quadrant', 'Osseous 4+', 'Periodontic', 1095.00),
('D4261', 'Osseous surgery - one to three contiguous teeth per quadrant', 'Osseous 1-3', 'Periodontic', 795.00),
('D4341', 'Periodontal scaling and root planing - four or more teeth per quadrant', 'SRP 4+/quad', 'Periodontic', 295.00),
('D4342', 'Periodontal scaling and root planing - one to three teeth per quadrant', 'SRP 1-3/quad', 'Periodontic', 195.00),
('D4346', 'Scaling in presence of generalized moderate or severe gingival inflammation', 'Full mouth scaling', 'Periodontic', 195.00),
('D4355', 'Full mouth debridement to enable a comprehensive oral evaluation', 'FMD', 'Periodontic', 175.00),
-- Prosthodontic Removable (D5000-D5899)
('D5110', 'Complete denture - maxillary', 'Upper denture', 'Prosthodontic Removable', 1595.00),
('D5120', 'Complete denture - mandibular', 'Lower denture', 'Prosthodontic Removable', 1595.00),
('D5130', 'Immediate denture - maxillary', 'Upper imm denture', 'Prosthodontic Removable', 1795.00),
('D5140', 'Immediate denture - mandibular', 'Lower imm denture', 'Prosthodontic Removable', 1795.00),
('D5211', 'Upper partial denture - resin base', 'Upper partial', 'Prosthodontic Removable', 1295.00),
('D5212', 'Lower partial denture - resin base', 'Lower partial', 'Prosthodontic Removable', 1295.00),
-- Prosthodontic Fixed (D6000-D6199)
('D6010', 'Surgical placement of implant body: endosteal implant', 'Implant placement', 'Prosthodontic Fixed', 1895.00),
('D6051', 'Interim abutment', 'Interim abutment', 'Prosthodontic Fixed', 395.00),
('D6056', 'Prefabricated abutment - includes modification and placement', 'Prefab abutment', 'Prosthodontic Fixed', 595.00),
('D6057', 'Custom fabricated abutment - includes placement', 'Custom abutment', 'Prosthodontic Fixed', 895.00),
('D6058', 'Implant supported crown - porcelain fused to predominantly base alloy', 'Impl crown PFM base', 'Prosthodontic Fixed', 1595.00),
('D6059', 'Implant supported crown - porcelain fused to noble alloy', 'Impl crown PFM noble', 'Prosthodontic Fixed', 1795.00),
('D6065', 'Implant supported porcelain/ceramic crown', 'Impl all-ceramic crown', 'Prosthodontic Fixed', 1895.00),
('D6066', 'Implant supported crown - predominantly base alloy', 'Impl metal crown base', 'Prosthodontic Fixed', 1395.00),
('D6067', 'Implant supported crown - noble alloy', 'Impl metal crown noble', 'Prosthodontic Fixed', 1595.00),
('D6068', 'Implant supported retainer - porcelain fused to predominantly base alloy', 'Impl retainer PFM', 'Prosthodontic Fixed', 1495.00),
-- Oral Surgery (D7000-D7999)
('D7140', 'Extraction, erupted tooth or exposed root', 'Simple extraction', 'Oral Surgery', 195.00),
('D7210', 'Extraction, erupted tooth requiring removal of bone and/or sectioning of tooth', 'Surgical extraction', 'Oral Surgery', 295.00),
('D7220', 'Removal of impacted tooth - soft tissue', 'Impaction soft', 'Oral Surgery', 395.00),
('D7230', 'Removal of impacted tooth - partially bony', 'Impaction partial', 'Oral Surgery', 495.00),
('D7240', 'Removal of impacted tooth - completely bony', 'Impaction full', 'Oral Surgery', 595.00),
('D7241', 'Removal of impacted tooth - completely bony, with unusual surgical complications', 'Impaction complex', 'Oral Surgery', 695.00),
('D7250', 'Removal of residual tooth roots', 'Root removal', 'Oral Surgery', 295.00),
('D7310', 'Alveoloplasty in conjunction with extractions - four or more teeth per quadrant', 'Alveoloplasty 4+', 'Oral Surgery', 395.00),
('D7311', 'Alveoloplasty in conjunction with extractions - one to three teeth per quadrant', 'Alveoloplasty 1-3', 'Oral Surgery', 295.00)
ON CONFLICT (ada_code) DO NOTHING;
